### ISSUE TITLE
Chunking issue

### ISSUE THREAD

**Issue by exander77** [MER-C/wiki-java#187]
I had to change:
```
        log2_upload_size = Integer.parseInt(props.getProperty("loguploadsize", "22")); // 4 MB
```
to:
```
        log2_upload_size = Integer.parseInt(props.getProperty("loguploadsize", "21")); // 2 MB
```
Otherwise, uploads are rejected when they are above a certain size.

**Comment by exander77** [comment]
No. It is not a solution, the problem still occurs. There is some chunking problem.

**Comment by MER-C** [comment]
This works for me - one of the test images I uploaded to test and verify #186 was 11 MB.

https://test.wikipedia.org/wiki/File:Test1235.jpg

Please provide examples of images that are broken.

**Comment by exander77** [comment]
[vicuna.zip](https://github.com/MER-C/wiki-java/files/7921375/vicuna.zip)

2 out of 3 of these doesn't work.

**Comment by MER-C** [comment]
jshell> test.upload(new File("IMG_20220117_122405.jpg"), "File:Test1236.jpg", "Test image", "blah")
Jan 24, 2022 7:15:05 PM Wiki getPageInfo
INFO: Fetching URL https://test.wikipedia.org/w/api.php?&maxlag=5&prop=info&inprop=protection%7Cdisplaytitle%7Cwatchers&format=xml&action=query
Jan 24, 2022 7:15:05 PM Wiki getPageInfo
INFO: [test.wikipedia.org] Successfully retrieved page info for 1 pages.
Jan 24, 2022 7:15:05 PM Wiki getToken
INFO: Fetching URL https://test.wikipedia.org/w/api.php?&maxlag=5&meta=tokens&format=xml&action=query&type=csrf
Jan 24, 2022 7:15:06 PM Wiki upload
INFO: Fetching URL https://test.wikipedia.org/w/api.php?&maxlag=5&format=xml&action=upload
|  Exception java.lang.UnknownError: MW API error. Server response was: <?xml version="1.0"?><api servedby="mw1424"><error code="badupload" info="The file for &quot;file&quot; was only partially uploaded." xml:space="preserve">See https://test.wikipedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &amp;lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&amp;gt; for notice of API deprecations and breaking changes.</error></api>
|        at Wiki.detectUncheckedErrors (Wiki.java:8380)
|        at Wiki.checkErrorsAndUpdateStatus (Wiki.java:8456)
|        at Wiki.upload (Wiki.java:4390)
|        at (#4:1)

This is not a chunking issue because this should have uploaded in one go.

**Comment by exander77** [comment]
@MER-C Yes, it is more of a problem with not chunking. But I am not sure what is the issue, I lowered it to 2M and it still problem appeared with some files.

**Comment by exander77** [comment]
@MER-C The issue exists. Vicuna cannot upload some files because of this.

**Comment by MER-C** [comment]
Did you test the new change? The file for which the log is pasted above uploaded successfully: https://test.wikipedia.org/wiki/File:Test1236.jpg

**Comment by exander77** [comment]
@MER-C Oh, it is fixed here? https://github.com/MER-C/wiki-java/commit/d2706166a1e06db6d3b66c74dea3de26cc4142c9

Will test.
